### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by zeinalii** [ubco-W2020WT1-data301/course-project-solo_331#2]
## High priority (must-fix)

- [x] add a structure to your report. It is better to have an introduction that gives the reader some information about the data and your question. 

- [x] Printing the dataset alone does not explain the data. You need to add a section called dataset, and explain the data. What are the columns and what do they show?

- [x] Add a section called analysis, and explain why exactly you chose that specific method of analysis to answer your questions. Why do you think that method of visualization would help you to answer the questions.

- [x] Just graphs alone do not answer your questions. You need to explain how those visualizations answer your questions. Try to explain the plots.

- [x] Your plots don't have a unit. All numerical properties have to have a unit.

- [x] Add title to your graphs. Some of them don't have one.

- [x] The last 2 bar graphs are too messy. Try changing the labels to something simpler.

**Comment by yohenthounaojam** [comment]
The last 2 graphs' label looks messy. However, I am confused as to how to change the date as it is needed.
